const express = require('express');
const Recipe = require('../models/Recipe');

const router = express.Router();
// NOTE: Do not cache demo mode at module-load time.
// Read process.env.DEMO_MODE inside each handler so fallback from DB failures works.

// Demo in-memory recipes
const demoRecipes = [
  {
    id: '1',
    title: 'Vegan Buddha Bowl',
    description: 'Nourishing bowl with quinoa, chickpeas, and fresh vegetables.',
    ingredients: [
      { name: 'Quinoa', quantity: '1 cup', category: 'grains' },
      { name: 'Chickpeas', quantity: '1 can', category: 'canned' },
      { name: 'Spinach', quantity: '2 cups', category: 'produce' },
      { name: 'Avocado', quantity: '1', category: 'produce' },
      { name: 'Cherry tomatoes', quantity: '1 cup', category: 'produce' },
    ],
    steps: ['Cook quinoa according to package instructions', 'Drain and rinse chickpeas, season and roast', 'Arrange all ingredients in a bowl', 'Drizzle with tahini dressing'],
    prepTime: 20,
    cookTime: 25,
    diet: 'vegan',
    cuisines: ['fusion'],
    images: [],
    rating: 4.6,
  },
  {
    id: '2',
    title: 'Gluten-Free Chicken Stir Fry',
    description: 'Quick and healthy stir fry with tamari sauce and fresh vegetables.',
    ingredients: [
      { name: 'Chicken breast', quantity: '500g', category: 'meat' },
      { name: 'Bell pepper', quantity: '2', category: 'produce' },
      { name: 'Tamari', quantity: '3 tbsp', category: 'condiments' },
      { name: 'Broccoli', quantity: '2 cups', category: 'produce' },
      { name: 'Ginger', quantity: '1 tbsp', category: 'spices' },
    ],
    steps: ['Slice chicken and vegetables', 'Heat oil in wok', 'Stir fry chicken until cooked', 'Add vegetables and tamari sauce', 'Serve over rice'],
    prepTime: 15,
    cookTime: 12,
    diet: 'gluten-free',
    cuisines: ['asian'],
    images: [],
    rating: 4.2,
  },
  {
    id: '3',
    title: 'Mediterranean Pasta Salad',
    description: 'Fresh pasta salad with olives, feta, and Mediterranean herbs.',
    ingredients: [
      { name: 'Pasta', quantity: '300g', category: 'grains' },
      { name: 'Feta cheese', quantity: '200g', category: 'dairy' },
      { name: 'Olives', quantity: '1 cup', category: 'canned' },
      { name: 'Cherry tomatoes', quantity: '2 cups', category: 'produce' },
      { name: 'Cucumber', quantity: '1', category: 'produce' },
      { name: 'Olive oil', quantity: '4 tbsp', category: 'condiments' },
    ],
    steps: ['Cook pasta and cool', 'Chop vegetables', 'Mix all ingredients', 'Dress with olive oil and herbs', 'Chill before serving'],
    prepTime: 25,
    cookTime: 10,
    diet: 'vegetarian',
    cuisines: ['mediterranean'],
    images: [],
    rating: 4.4,
  },
  {
    id: '4',
    title: 'Keto Salmon with Asparagus',
    description: 'Perfectly baked salmon with roasted asparagus and lemon.',
    ingredients: [
      { name: 'Salmon fillets', quantity: '4', category: 'meat' },
      { name: 'Asparagus', quantity: '500g', category: 'produce' },
      { name: 'Lemon', quantity: '2', category: 'produce' },
      { name: 'Olive oil', quantity: '3 tbsp', category: 'condiments' },
      { name: 'Garlic', quantity: '3 cloves', category: 'produce' },
    ],
    steps: ['Preheat oven to 400°F', 'Season salmon with herbs', 'Toss asparagus with oil and garlic', 'Bake together for 15 minutes', 'Serve with lemon wedges'],
    prepTime: 10,
    cookTime: 15,
    diet: 'keto',
    cuisines: ['american'],
    images: [],
    rating: 4.7,
  },
  {
    id: '5',
    title: 'Thai Green Curry',
    description: 'Authentic Thai green curry with coconut milk and fresh basil.',
    ingredients: [
      { name: 'Green curry paste', quantity: '3 tbsp', category: 'condiments' },
      { name: 'Coconut milk', quantity: '400ml', category: 'canned' },
      { name: 'Chicken thigh', quantity: '500g', category: 'meat' },
      { name: 'Thai basil', quantity: '1 cup', category: 'produce' },
      { name: 'Eggplant', quantity: '2', category: 'produce' },
      { name: 'Fish sauce', quantity: '2 tbsp', category: 'condiments' },
    ],
    steps: ['Fry curry paste in oil', 'Add coconut milk gradually', 'Add chicken and vegetables', 'Simmer until tender', 'Garnish with basil'],
    prepTime: 20,
    cookTime: 25,
    diet: 'none',
    cuisines: ['thai'],
    images: [],
    rating: 4.8,
  },
  {
    id: '6',
    title: 'Quinoa Stuffed Bell Peppers',
    description: 'Colorful bell peppers stuffed with quinoa, vegetables, and herbs.',
    ingredients: [
      { name: 'Bell peppers', quantity: '4', category: 'produce' },
      { name: 'Quinoa', quantity: '1 cup', category: 'grains' },
      { name: 'Black beans', quantity: '1 can', category: 'canned' },
      { name: 'Corn', quantity: '1 cup', category: 'produce' },
      { name: 'Onion', quantity: '1', category: 'produce' },
      { name: 'Cheese', quantity: '1 cup', category: 'dairy' },
    ],
    steps: ['Cook quinoa', 'Hollow out peppers', 'Mix quinoa with vegetables', 'Stuff peppers', 'Bake until tender'],
    prepTime: 30,
    cookTime: 35,
    diet: 'vegetarian',
    cuisines: ['mexican'],
    images: [],
    rating: 4.3,
  },
  {
    id: '7',
    title: 'Japanese Miso Ramen',
    description: 'Rich and flavorful miso ramen with soft-boiled eggs and vegetables.',
    ingredients: [
      { name: 'Ramen noodles', quantity: '2 packs', category: 'grains' },
      { name: 'Miso paste', quantity: '3 tbsp', category: 'condiments' },
      { name: 'Eggs', quantity: '2', category: 'dairy' },
      { name: 'Green onions', quantity: '3', category: 'produce' },
      { name: 'Mushrooms', quantity: '200g', category: 'produce' },
      { name: 'Nori', quantity: '2 sheets', category: 'misc' },
    ],
    steps: ['Prepare soft-boiled eggs', 'Make miso broth', 'Cook noodles', 'Sauté mushrooms', 'Assemble bowl with toppings'],
    prepTime: 25,
    cookTime: 20,
    diet: 'vegetarian',
    cuisines: ['japanese'],
    images: [],
    rating: 4.6,
  },
  {
    id: '8',
    title: 'Paleo Beef Tacos',
    description: 'Grain-free tacos with seasoned ground beef and fresh toppings.',
    ingredients: [
      { name: 'Ground beef', quantity: '500g', category: 'meat' },
      { name: 'Lettuce leaves', quantity: '8', category: 'produce' },
      { name: 'Avocado', quantity: '2', category: 'produce' },
      { name: 'Tomatoes', quantity: '2', category: 'produce' },
      { name: 'Lime', quantity: '2', category: 'produce' },
      { name: 'Cumin', quantity: '1 tsp', category: 'spices' },
    ],
    steps: ['Brown ground beef with spices', 'Prepare fresh toppings', 'Warm lettuce leaves', 'Assemble tacos', 'Serve with lime'],
    prepTime: 15,
    cookTime: 10,
    diet: 'paleo',
    cuisines: ['mexican'],
    images: [],
    rating: 4.5,
  },
  {
    id: '9',
    title: 'Indian Butter Chicken',
    description: 'Creamy and aromatic butter chicken with basmati rice.',
    ingredients: [
      { name: 'Chicken breast', quantity: '600g', category: 'meat' },
      { name: 'Tomato sauce', quantity: '400g', category: 'canned' },
      { name: 'Heavy cream', quantity: '200ml', category: 'dairy' },
      { name: 'Garam masala', quantity: '2 tsp', category: 'spices' },
      { name: 'Ginger', quantity: '2 tbsp', category: 'produce' },
      { name: 'Garlic', quantity: '4 cloves', category: 'produce' },
    ],
    steps: ['Marinate chicken in yogurt and spices', 'Cook chicken until golden', 'Make tomato-cream sauce', 'Simmer chicken in sauce', 'Serve with rice'],
    prepTime: 30,
    cookTime: 25,
    diet: 'none',
    cuisines: ['indian'],
    images: [],
    rating: 4.9,
  },
  {
    id: '10',
    title: 'Greek Lemon Chicken',
    description: 'Tender chicken with lemon, oregano, and roasted potatoes.',
    ingredients: [
      { name: 'Chicken pieces', quantity: '1 whole', category: 'meat' },
      { name: 'Potatoes', quantity: '6', category: 'produce' },
      { name: 'Lemons', quantity: '3', category: 'produce' },
      { name: 'Oregano', quantity: '2 tbsp', category: 'spices' },
      { name: 'Olive oil', quantity: '1/2 cup', category: 'condiments' },
    ],
    steps: ['Marinate chicken with lemon and herbs', 'Cut potatoes into wedges', 'Roast together in oven', 'Baste with pan juices', 'Serve hot'],
    prepTime: 20,
    cookTime: 60,
    diet: 'none',
    cuisines: ['greek'],
    images: [],
    rating: 4.4,
  },
  {
    id: '11',
    title: 'Vegan Mushroom Risotto',
    description: 'Creamy risotto made with mushroom broth and nutritional yeast.',
    ingredients: [
      { name: 'Arborio rice', quantity: '300g', category: 'grains' },
      { name: 'Mixed mushrooms', quantity: '400g', category: 'produce' },
      { name: 'Vegetable broth', quantity: '1L', category: 'canned' },
      { name: 'Nutritional yeast', quantity: '1/4 cup', category: 'misc' },
      { name: 'White wine', quantity: '1/2 cup', category: 'condiments' },
    ],
    steps: ['Sauté mushrooms', 'Toast rice with onions', 'Add wine and reduce', 'Gradually add warm broth', 'Stir in nutritional yeast'],
    prepTime: 15,
    cookTime: 30,
    diet: 'vegan',
    cuisines: ['italian'],
    images: [],
    rating: 4.3,
  },
  {
    id: '12',
    title: 'Korean Bibimbap',
    description: 'Mixed rice bowl with vegetables, egg, and spicy gochujang sauce.',
    ingredients: [
      { name: 'Rice', quantity: '2 cups', category: 'grains' },
      { name: 'Spinach', quantity: '200g', category: 'produce' },
      { name: 'Carrots', quantity: '2', category: 'produce' },
      { name: 'Bean sprouts', quantity: '200g', category: 'produce' },
      { name: 'Eggs', quantity: '2', category: 'dairy' },
      { name: 'Gochujang', quantity: '2 tbsp', category: 'condiments' },
    ],
    steps: ['Cook rice', 'Prepare seasoned vegetables', 'Fry eggs sunny-side up', 'Arrange in bowls', 'Serve with gochujang'],
    prepTime: 40,
    cookTime: 20,
    diet: 'vegetarian',
    cuisines: ['korean'],
    images: [],
    rating: 4.7,
  },
  {
    id: '13',
    title: 'French Coq au Vin',
    description: 'Classic French chicken braised in red wine with vegetables.',
    ingredients: [
      { name: 'Chicken pieces', quantity: '1.5kg', category: 'meat' },
      { name: 'Red wine', quantity: '750ml', category: 'condiments' },
      { name: 'Bacon', quantity: '200g', category: 'meat' },
      { name: 'Pearl onions', quantity: '300g', category: 'produce' },
      { name: 'Mushrooms', quantity: '250g', category: 'produce' },
      { name: 'Thyme', quantity: '2 sprigs', category: 'spices' },
    ],
    steps: ['Brown chicken and bacon', 'Sauté vegetables', 'Deglaze with wine', 'Braise slowly until tender', 'Serve with crusty bread'],
    prepTime: 30,
    cookTime: 90,
    diet: 'none',
    cuisines: ['french'],
    images: [],
    rating: 4.8,
  },
  {
    id: '14',
    title: 'Moroccan Tagine',
    description: 'Aromatic stew with lamb, apricots, and warm spices.',
    ingredients: [
      { name: 'Lamb shoulder', quantity: '800g', category: 'meat' },
      { name: 'Dried apricots', quantity: '200g', category: 'misc' },
      { name: 'Onions', quantity: '2', category: 'produce' },
      { name: 'Cinnamon', quantity: '1 tsp', category: 'spices' },
      { name: 'Almonds', quantity: '100g', category: 'misc' },
      { name: 'Couscous', quantity: '300g', category: 'grains' },
    ],
    steps: ['Brown lamb pieces', 'Add onions and spices', 'Add apricots and broth', 'Simmer until tender', 'Serve over couscous'],
    prepTime: 25,
    cookTime: 120,
    diet: 'none',
    cuisines: ['moroccan'],
    images: [],
    rating: 4.6,
  },
  {
    id: '15',
    title: 'Brazilian Feijoada',
    description: 'Traditional black bean stew with pork and sausages.',
    ingredients: [
      { name: 'Black beans', quantity: '500g', category: 'canned' },
      { name: 'Pork shoulder', quantity: '400g', category: 'meat' },
      { name: 'Chorizo', quantity: '200g', category: 'meat' },
      { name: 'Orange', quantity: '2', category: 'produce' },
      { name: 'Rice', quantity: '2 cups', category: 'grains' },
      { name: 'Collard greens', quantity: '300g', category: 'produce' },
    ],
    steps: ['Soak beans overnight', 'Brown meats', 'Simmer beans with meats', 'Season with orange zest', 'Serve with rice and greens'],
    prepTime: 30,
    cookTime: 180,
    diet: 'none',
    cuisines: ['brazilian'],
    images: [],
    rating: 4.5,
  },
  {
    id: '16',
    title: 'Vietnamese Pho',
    description: 'Aromatic beef noodle soup with fresh herbs and spices.',
    ingredients: [
      { name: 'Rice noodles', quantity: '400g', category: 'grains' },
      { name: 'Beef bones', quantity: '1kg', category: 'meat' },
      { name: 'Star anise', quantity: '4', category: 'spices' },
      { name: 'Bean sprouts', quantity: '200g', category: 'produce' },
      { name: 'Thai basil', quantity: '1 bunch', category: 'produce' },
      { name: 'Lime', quantity: '2', category: 'produce' },
    ],
    steps: ['Make bone broth with spices', 'Cook rice noodles', 'Slice beef thinly', 'Assemble bowls', 'Serve with fresh herbs'],
    prepTime: 45,
    cookTime: 240,
    diet: 'none',
    cuisines: ['vietnamese'],
    images: [],
    rating: 4.9,
  },
  {
    id: '17',
    title: 'Spanish Paella',
    description: 'Traditional seafood paella with saffron rice and fresh shellfish.',
    ingredients: [
      { name: 'Bomba rice', quantity: '400g', category: 'grains' },
      { name: 'Saffron', quantity: '1 pinch', category: 'spices' },
      { name: 'Shrimp', quantity: '300g', category: 'meat' },
      { name: 'Mussels', quantity: '500g', category: 'meat' },
      { name: 'Green beans', quantity: '200g', category: 'produce' },
      { name: 'Tomatoes', quantity: '2', category: 'produce' },
    ],
    steps: ['Heat paella pan', 'Sauté vegetables', 'Add rice and saffron', 'Add seafood', 'Simmer until rice is tender'],
    prepTime: 30,
    cookTime: 25,
    diet: 'none',
    cuisines: ['spanish'],
    images: [],
    rating: 4.7,
  },
  {
    id: '18',
    title: 'Turkish Kebabs',
    description: 'Grilled lamb kebabs with yogurt sauce and flatbread.',
    ingredients: [
      { name: 'Ground lamb', quantity: '600g', category: 'meat' },
      { name: 'Yogurt', quantity: '200g', category: 'dairy' },
      { name: 'Flatbread', quantity: '4', category: 'grains' },
      { name: 'Red onion', quantity: '1', category: 'produce' },
      { name: 'Parsley', quantity: '1 bunch', category: 'produce' },
      { name: 'Sumac', quantity: '1 tsp', category: 'spices' },
    ],
    steps: ['Mix lamb with spices', 'Form into kebabs', 'Grill until cooked', 'Make yogurt sauce', 'Serve with bread and salad'],
    prepTime: 25,
    cookTime: 15,
    diet: 'none',
    cuisines: ['turkish'],
    images: [],
    rating: 4.4,
  },
  {
    id: '19',
    title: 'Ethiopian Doro Wat',
    description: 'Spicy chicken stew with berbere spice and hard-boiled eggs.',
    ingredients: [
      { name: 'Chicken pieces', quantity: '1kg', category: 'meat' },
      { name: 'Berbere spice', quantity: '3 tbsp', category: 'spices' },
      { name: 'Eggs', quantity: '6', category: 'dairy' },
      { name: 'Onions', quantity: '4', category: 'produce' },
      { name: 'Injera bread', quantity: '4', category: 'grains' },
      { name: 'Butter', quantity: '100g', category: 'dairy' },
    ],
    steps: ['Caramelize onions slowly', 'Add berbere and chicken', 'Simmer with eggs', 'Cook until tender', 'Serve with injera'],
    prepTime: 40,
    cookTime: 90,
    diet: 'none',
    cuisines: ['ethiopian'],
    images: [],
    rating: 4.6,
  },
  {
    id: '20',
    title: 'Russian Borscht',
    description: 'Traditional beet soup with cabbage and sour cream.',
    ingredients: [
      { name: 'Fresh beets', quantity: '4', category: 'produce' },
      { name: 'Cabbage', quantity: '300g', category: 'produce' },
      { name: 'Beef broth', quantity: '1L', category: 'canned' },
      { name: 'Sour cream', quantity: '200g', category: 'dairy' },
      { name: 'Dill', quantity: '2 tbsp', category: 'produce' },
      { name: 'Potatoes', quantity: '3', category: 'produce' },
    ],
    steps: ['Roast beets until tender', 'Grate beets and add to broth', 'Add vegetables', 'Simmer until soft', 'Serve with sour cream and dill'],
    prepTime: 30,
    cookTime: 60,
    diet: 'none',
    cuisines: ['russian'],
    images: [],
    rating: 4.3,
  },
  {
    id: '21',
    title: 'Masala Dosa',
    description: 'Crispy rice-lentil crepe with spiced potato masala and chutney.',
    ingredients: [
      { name: 'Rice', quantity: '2 cups', category: 'grains' },
      { name: 'Urad dal', quantity: '1 cup', category: 'grains' },
      { name: 'Potatoes', quantity: '3', category: 'produce' },
      { name: 'Onion', quantity: '1', category: 'produce' },
      { name: 'Curry leaves', quantity: '1 sprig', category: 'produce' },
    ],
    steps: ['Soak rice and dal', 'Grind to batter and ferment', 'Make potato masala', 'Spread batter on tawa', 'Fill and fold dosa'],
    prepTime: 30,
    cookTime: 20,
    diet: 'vegetarian',
    cuisines: ['south indian'],
    images: [],
    rating: 4.8,
  },
  {
    id: '22',
    title: 'Punjabi Chole Bhature',
    description: 'Spiced chickpea curry served with fluffy fried bread.',
    ingredients: [
      { name: 'Chickpeas', quantity: '2 cups', category: 'canned' },
      { name: 'All-purpose flour', quantity: '2 cups', category: 'grains' },
      { name: 'Yogurt', quantity: '1/2 cup', category: 'dairy' },
      { name: 'Onions', quantity: '2', category: 'produce' },
      { name: 'Chole masala', quantity: '2 tbsp', category: 'spices' },
    ],
    steps: ['Pressure cook chickpeas', 'Sauté onion-tomato masala', 'Simmer chole with spices', 'Knead bhature dough', 'Roll and fry bhature'],
    prepTime: 40,
    cookTime: 30,
    diet: 'none',
    cuisines: ['punjabi'],
    images: [],
    rating: 4.7,
  },
  {
    id: '23',
    title: 'Gujarati Khaman Dhokla',
    description: 'Steamed gram flour cake tempered with mustard and curry leaves.',
    ingredients: [
      { name: 'Gram flour', quantity: '1.5 cups', category: 'grains' },
      { name: 'Yogurt', quantity: '1/2 cup', category: 'dairy' },
      { name: 'Eno fruit salt', quantity: '1 tsp', category: 'misc' },
      { name: 'Mustard seeds', quantity: '1 tsp', category: 'spices' },
      { name: 'Green chilies', quantity: '2', category: 'produce' },
    ],
    steps: ['Mix batter with yogurt', 'Add fruit salt and steam', 'Temper with mustard and chilies', 'Cut and serve with chutney'],
    prepTime: 15,
    cookTime: 20,
    diet: 'vegetarian',
    cuisines: ['gujarati'],
    images: [],
    rating: 4.6,
  },
  {
    id: '24',
    title: 'Paneer Tikka',
    description: 'Marinated paneer cubes grilled with peppers and onions.',
    ingredients: [
      { name: 'Paneer', quantity: '400g', category: 'dairy' },
      { name: 'Bell peppers', quantity: '2', category: 'produce' },
      { name: 'Yogurt', quantity: '1 cup', category: 'dairy' },
      { name: 'Tikka masala', quantity: '2 tbsp', category: 'spices' },
      { name: 'Lemon', quantity: '1', category: 'produce' },
    ],
    steps: ['Mix yogurt with spices', 'Marinate paneer and veggies', 'Skewer pieces', 'Grill or bake until charred'],
    prepTime: 20,
    cookTime: 15,
    diet: 'vegetarian',
    cuisines: ['punjabi'],
    images: [],
    rating: 4.5,
  },
  {
    id: '25',
    title: 'Hyderabadi Chicken Biryani',
    description: 'Layered basmati rice and spiced chicken cooked with saffron.',
    ingredients: [
      { name: 'Basmati rice', quantity: '2 cups', category: 'grains' },
      { name: 'Chicken', quantity: '800g', category: 'meat' },
      { name: 'Ghee', quantity: '3 tbsp', category: 'condiments' },
      { name: 'Fried onions', quantity: '1 cup', category: 'produce' },
      { name: 'Saffron', quantity: '1 pinch', category: 'spices' },
    ],
    steps: ['Marinate chicken with spices', 'Parboil rice', 'Layer rice and chicken', 'Cook on dum until aromatic'],
    prepTime: 40,
    cookTime: 40,
    diet: 'none',
    cuisines: ['andhra'],
    images: [],
    rating: 4.9,
  },
  {
    id: '26',
    title: 'Bengali Rasgulla',
    description: 'Soft cottage cheese balls simmered in sugar syrup.',
    ingredients: [
      { name: 'Milk', quantity: '1L', category: 'dairy' },
      { name: 'Lemon juice', quantity: '2 tbsp', category: 'produce' },
      { name: 'Sugar', quantity: '1 cup', category: 'misc' },
      { name: 'Cardamom', quantity: '4 pods', category: 'spices' },
    ],
    steps: ['Curdle milk to make chenna', 'Knead and shape balls', 'Boil in sugar syrup', 'Flavor with cardamom'],
    prepTime: 25,
    cookTime: 30,
    diet: 'vegetarian',
    cuisines: ['bengali'],
    images: [],
    rating: 4.4,
  },
  {
    id: '27',
    title: 'Mumbai Pav Bhaji',
    description: 'Mashed spiced vegetable curry served with buttered bread rolls.',
    ingredients: [
      { name: 'Potatoes', quantity: '3', category: 'produce' },
      { name: 'Cauliflower', quantity: '200g', category: 'produce' },
      { name: 'Peas', quantity: '1 cup', category: 'produce' },
      { name: 'Pav buns', quantity: '8', category: 'grains' },
      { name: 'Pav bhaji masala', quantity: '2 tbsp', category: 'spices' },
    ],
    steps: ['Boil and mash veggies', 'Cook masala with butter', 'Toast pav with butter', 'Serve with lemon and onions'],
    prepTime: 20,
    cookTime: 25,
    diet: 'vegetarian',
    cuisines: ['maharashtrian'],
    images: [],
    rating: 4.6,
  },
  {
    id: '28',
    title: 'Rajasthani Dal Baati Churma',
    description: 'Baked wheat rolls with spiced lentils and sweet churma.',
    ingredients: [
      { name: 'Wheat flour', quantity: '2 cups', category: 'grains' },
      { name: 'Toor dal', quantity: '1 cup', category: 'grains' },
      { name: 'Ghee', quantity: '4 tbsp', category: 'condiments' },
      { name: 'Jaggery', quantity: '1/2 cup', category: 'misc' },
      { name: 'Cumin seeds', quantity: '1 tsp', category: 'spices' },
    ],
    steps: ['Knead stiff dough and bake baati', 'Cook dal with spices', 'Crush baati with ghee and jaggery for churma', 'Serve together'],
    prepTime: 30,
    cookTime: 35,
    diet: 'vegetarian',
    cuisines: ['rajasthani'],
    images: [],
    rating: 4.5,
  },
  {
    id: '29',
    title: 'Kerala Fish Curry',
    description: 'Tangy coconut-based curry with fish, curry leaves, and kokum.',
    ingredients: [
      { name: 'Fish fillets', quantity: '600g', category: 'meat' },
      { name: 'Coconut milk', quantity: '400ml', category: 'canned' },
      { name: 'Kokum or tamarind', quantity: '1 tbsp', category: 'misc' },
      { name: 'Mustard seeds', quantity: '1 tsp', category: 'spices' },
      { name: 'Curry leaves', quantity: '1 sprig', category: 'produce' },
    ],
    steps: ['Temper mustard and curry leaves', 'Add spices and coconut milk', 'Simmer fish gently', 'Rest and serve with rice'],
    prepTime: 20,
    cookTime: 20,
    diet: 'none',
    cuisines: ['kerala'],
    images: [],
    rating: 4.7,
  },
  {
    id: '30',
    title: 'South Indian Sambar Rice',
    description: 'Comforting rice mixed with hearty lentil-vegetable sambar.',
    ingredients: [
      { name: 'Rice', quantity: '2 cups', category: 'grains' },
      { name: 'Toor dal', quantity: '1 cup', category: 'grains' },
      { name: 'Drumstick & vegetables', quantity: '2 cups', category: 'produce' },
      { name: 'Sambar powder', quantity: '2 tbsp', category: 'spices' },
      { name: 'Tamarind', quantity: '1 tbsp', category: 'misc' },
    ],
    steps: ['Cook dal and rice separately', 'Make sambar with vegetables', 'Combine rice with sambar', 'Garnish with ghee and coriander'],
    prepTime: 20,
    cookTime: 25,
    diet: 'vegetarian',
    cuisines: ['south indian'],
    images: [],
    rating: 4.6,
  },
  {
    id: '31',
    title: 'Turkish Kebab Platter',
    description: 'Mixed grilled meats with rice, salad, and yogurt sauce.',
    ingredients: [
      { name: 'Lamb mince', quantity: '300g', category: 'meat' },
      { name: 'Chicken breast', quantity: '300g', category: 'meat' },
      { name: 'Rice pilaf', quantity: '2 cups', category: 'grains' },
      { name: 'Greek yogurt', quantity: '1 cup', category: 'dairy' },
      { name: 'Sumac', quantity: '1 tsp', category: 'spices' },
    ],
    steps: ['Season and shape kebabs', 'Grill until charred', 'Prepare rice pilaf', 'Make yogurt sauce', 'Serve with fresh salad'],
    prepTime: 30,
    cookTime: 20,
    diet: 'none',
    cuisines: ['turkish'],
    images: [],
    rating: 4.6,
  },
  {
    id: '32',
    title: 'Chinese Kung Pao Chicken',
    description: 'Spicy stir-fried chicken with peanuts and vegetables.',
    ingredients: [
      { name: 'Chicken thigh', quantity: '500g', category: 'meat' },
      { name: 'Peanuts', quantity: '1/2 cup', category: 'misc' },
      { name: 'Sichuan peppercorns', quantity: '1 tsp', category: 'spices' },
      { name: 'Dried chilies', quantity: '6', category: 'spices' },
      { name: 'Soy sauce', quantity: '3 tbsp', category: 'condiments' },
    ],
    steps: ['Marinate chicken pieces', 'Stir-fry with aromatics', 'Add sauce and peanuts', 'Toss until glazed', 'Serve with steamed rice'],
    prepTime: 20,
    cookTime: 15,
    diet: 'none',
    cuisines: ['chinese'],
    images: [],
    rating: 4.5,
  },
  {
    id: '33',
    title: 'Mexican Pozole Rojo',
    description: 'Traditional hominy soup with pork and red chile broth.',
    ingredients: [
      { name: 'Pork shoulder', quantity: '800g', category: 'meat' },
      { name: 'Hominy', quantity: '2 cans', category: 'canned' },
      { name: 'Guajillo chiles', quantity: '6', category: 'spices' },
      { name: 'Cabbage', quantity: '1/4 head', category: 'produce' },
      { name: 'Radishes', quantity: '4', category: 'produce' },
    ],
    steps: ['Simmer pork until tender', 'Blend soaked chiles', 'Combine with hominy', 'Garnish with fresh toppings', 'Serve with lime'],
    prepTime: 30,
    cookTime: 120,
    diet: 'none',
    cuisines: ['mexican'],
    images: [],
    rating: 4.7,
  },
  {
    id: '34',
    title: 'Italian Osso Buco',
    description: 'Braised veal shanks with vegetables in white wine.',
    ingredients: [
      { name: 'Veal shanks', quantity: '4 pieces', category: 'meat' },
      { name: 'White wine', quantity: '1 cup', category: 'condiments' },
      { name: 'Carrots', quantity: '2', category: 'produce' },
      { name: 'Celery', quantity: '2 stalks', category: 'produce' },
      { name: 'Gremolata', quantity: '2 tbsp', category: 'misc' },
    ],
    steps: ['Brown veal shanks', 'Sauté mirepoix', 'Deglaze with wine', 'Braise slowly', 'Finish with gremolata'],
    prepTime: 25,
    cookTime: 150,
    diet: 'none',
    cuisines: ['italian'],
    images: [],
    rating: 4.8,
  },
  {
    id: '35',
    title: 'Japanese Chicken Teriyaki',
    description: 'Glazed chicken thighs with sweet teriyaki sauce.',
    ingredients: [
      { name: 'Chicken thighs', quantity: '6', category: 'meat' },
      { name: 'Soy sauce', quantity: '1/4 cup', category: 'condiments' },
      { name: 'Mirin', quantity: '2 tbsp', category: 'condiments' },
      { name: 'Sugar', quantity: '2 tbsp', category: 'misc' },
      { name: 'Sesame seeds', quantity: '1 tbsp', category: 'misc' },
    ],
    steps: ['Pan-fry chicken skin-side down', 'Flip and cook through', 'Add teriyaki sauce', 'Glaze until sticky', 'Garnish with sesame seeds'],
    prepTime: 10,
    cookTime: 20,
    diet: 'none',
    cuisines: ['japanese'],
    images: [],
    rating: 4.6,
  },
  {
    id: '36',
    title: 'Peruvian Ceviche',
    description: 'Fresh fish cured in citrus with onions and peppers.',
    ingredients: [
      { name: 'White fish', quantity: '500g', category: 'meat' },
      { name: 'Lime juice', quantity: '1/2 cup', category: 'produce' },
      { name: 'Red onion', quantity: '1', category: 'produce' },
      { name: 'Aji amarillo', quantity: '2', category: 'produce' },
      { name: 'Sweet potato', quantity: '2', category: 'produce' },
    ],
    steps: ['Dice fish finely', 'Marinate in lime juice', 'Add sliced onions and peppers', 'Let cure for 15 minutes', 'Serve with sweet potato'],
    prepTime: 25,
    cookTime: 0,
    diet: 'none',
    cuisines: ['peruvian'],
    images: [],
    rating: 4.7,
  },
  {
    id: '37',
    title: 'Lebanese Hummus Bowl',
    description: 'Creamy chickpea dip with tahini, served with vegetables.',
    ingredients: [
      { name: 'Chickpeas', quantity: '2 cups', category: 'canned' },
      { name: 'Tahini', quantity: '1/4 cup', category: 'condiments' },
      { name: 'Lemon juice', quantity: '3 tbsp', category: 'produce' },
      { name: 'Garlic', quantity: '3 cloves', category: 'produce' },
      { name: 'Pita bread', quantity: '4', category: 'grains' },
    ],
    steps: ['Blend chickpeas until smooth', 'Add tahini and lemon', 'Adjust consistency with water', 'Drizzle with olive oil', 'Serve with warm pita'],
    prepTime: 15,
    cookTime: 0,
    diet: 'vegan',
    cuisines: ['lebanese'],
    images: [],
    rating: 4.5,
  },
  {
    id: '38',
    title: 'German Sauerbraten',
    description: 'Marinated pot roast with sweet and sour gravy.',
    ingredients: [
      { name: 'Beef roast', quantity: '1.5kg', category: 'meat' },
      { name: 'Red wine vinegar', quantity: '1 cup', category: 'condiments' },
      { name: 'Gingersnaps', quantity: '6', category: 'misc' },
      { name: 'Onions', quantity: '2', category: 'produce' },
      { name: 'Bay leaves', quantity: '3', category: 'spices' },
    ],
    steps: ['Marinate beef for 3 days', 'Brown and braise slowly', 'Strain marinade for gravy', 'Thicken with gingersnaps', 'Serve with red cabbage'],
    prepTime: 30,
    cookTime: 180,
    diet: 'none',
    cuisines: ['german'],
    images: [],
    rating: 4.4,
  },
  {
    id: '39',
    title: 'Polish Pierogi',
    description: 'Potato dumplings with caramelized onions and sour cream.',
    ingredients: [
      { name: 'Flour', quantity: '3 cups', category: 'grains' },
      { name: 'Potatoes', quantity: '4', category: 'produce' },
      { name: 'Onions', quantity: '2', category: 'produce' },
      { name: 'Sour cream', quantity: '1 cup', category: 'dairy' },
      { name: 'Butter', quantity: '4 tbsp', category: 'dairy' },
    ],
    steps: ['Make dough and rest', 'Prepare potato filling', 'Roll and fill dumplings', 'Boil until they float', 'Sauté with onions'],
    prepTime: 60,
    cookTime: 30,
    diet: 'vegetarian',
    cuisines: ['polish'],
    images: [],
    rating: 4.6,
  },
  {
    id: '40',
    title: 'Argentine Empanadas',
    description: 'Baked pastries filled with seasoned beef and vegetables.',
    ingredients: [
      { name: 'Ground beef', quantity: '500g', category: 'meat' },
      { name: 'Empanada dough', quantity: '12 discs', category: 'grains' },
      { name: 'Onions', quantity: '2', category: 'produce' },
      { name: 'Hard-boiled eggs', quantity: '2', category: 'dairy' },
      { name: 'Olives', quantity: '1/2 cup', category: 'canned' },
    ],
    steps: ['Sauté beef with onions', 'Cool and add eggs and olives', 'Fill dough circles', 'Seal edges well', 'Bake until golden'],
    prepTime: 45,
    cookTime: 25,
    diet: 'none',
    cuisines: ['argentine'],
    images: [],
    rating: 4.5,
  },
  {
    id: '41',
    title: 'Swedish Meatballs',
    description: 'Tender meatballs in creamy gravy with lingonberry sauce.',
    ingredients: [
      { name: 'Ground beef and pork', quantity: '500g', category: 'meat' },
      { name: 'Breadcrumbs', quantity: '1/2 cup', category: 'grains' },
      { name: 'Heavy cream', quantity: '1 cup', category: 'dairy' },
      { name: 'Lingonberry jam', quantity: '3 tbsp', category: 'misc' },
      { name: 'Allspice', quantity: '1/2 tsp', category: 'spices' },
    ],
    steps: ['Mix meat with breadcrumbs', 'Form small meatballs', 'Brown in batches', 'Make cream gravy', 'Serve with lingonberries'],
    prepTime: 20,
    cookTime: 25,
    diet: 'none',
    cuisines: ['swedish'],
    images: [],
    rating: 4.7,
  },
  {
    id: '42',
    title: 'Caribbean Jerk Chicken',
    description: 'Spicy marinated chicken with tropical jerk seasoning.',
    ingredients: [
      { name: 'Chicken pieces', quantity: '1kg', category: 'meat' },
      { name: 'Scotch bonnet peppers', quantity: '2', category: 'produce' },
      { name: 'Allspice berries', quantity: '2 tbsp', category: 'spices' },
      { name: 'Lime juice', quantity: '1/4 cup', category: 'produce' },
      { name: 'Brown sugar', quantity: '2 tbsp', category: 'misc' },
    ],
    steps: ['Blend jerk marinade', 'Marinate chicken overnight', 'Grill over high heat', 'Baste with marinade', 'Serve with rice and peas'],
    prepTime: 20,
    cookTime: 30,
    diet: 'none',
    cuisines: ['caribbean'],
    images: [],
    rating: 4.8,
  },
  {
    id: '43',
    title: 'Hungarian Goulash',
    description: 'Hearty beef stew with paprika and vegetables.',
    ingredients: [
      { name: 'Beef chuck', quantity: '800g', category: 'meat' },
      { name: 'Paprika', quantity: '3 tbsp', category: 'spices' },
      { name: 'Onions', quantity: '3', category: 'produce' },
      { name: 'Tomatoes', quantity: '2', category: 'produce' },
      { name: 'Caraway seeds', quantity: '1 tsp', category: 'spices' },
    ],
    steps: ['Brown beef in batches', 'Sauté onions with paprika', 'Add tomatoes and broth', 'Simmer until tender', 'Serve with dumplings'],
    prepTime: 25,
    cookTime: 120,
    diet: 'none',
    cuisines: ['hungarian'],
    images: [],
    rating: 4.6,
  },
  {
    id: '44',
    title: 'Australian Meat Pie',
    description: 'Flaky pastry filled with seasoned ground meat.',
    ingredients: [
      { name: 'Ground beef', quantity: '600g', category: 'meat' },
      { name: 'Puff pastry', quantity: '2 sheets', category: 'grains' },
      { name: 'Worcestershire sauce', quantity: '2 tbsp', category: 'condiments' },
      { name: 'Beef stock', quantity: '1 cup', category: 'canned' },
      { name: 'Tomato sauce', quantity: '2 tbsp', category: 'condiments' },
    ],
    steps: ['Brown meat with onions', 'Add sauces and simmer', 'Line pie tins with pastry', 'Fill and top with pastry', 'Bake until golden'],
    prepTime: 30,
    cookTime: 35,
    diet: 'none',
    cuisines: ['australian'],
    images: [],
    rating: 4.4,
  },
  {
    id: '45',
    title: 'Norwegian Salmon',
    description: 'Cedar plank salmon with dill and mustard glaze.',
    ingredients: [
      { name: 'Salmon fillet', quantity: '800g', category: 'meat' },
      { name: 'Dijon mustard', quantity: '3 tbsp', category: 'condiments' },
      { name: 'Fresh dill', quantity: '1/4 cup', category: 'produce' },
      { name: 'Honey', quantity: '2 tbsp', category: 'misc' },
      { name: 'Cedar plank', quantity: '1', category: 'misc' },
    ],
    steps: ['Soak cedar plank', 'Mix glaze ingredients', 'Place salmon on plank', 'Brush with glaze', 'Grill until flaky'],
    prepTime: 15,
    cookTime: 20,
    diet: 'none',
    cuisines: ['norwegian'],
    images: [],
    rating: 4.7,
  },
  {
    id: '46',
    title: 'Egyptian Koshari',
    description: 'Mixed rice, lentils, and pasta with spicy tomato sauce.',
    ingredients: [
      { name: 'Rice', quantity: '1 cup', category: 'grains' },
      { name: 'Lentils', quantity: '1 cup', category: 'grains' },
      { name: 'Macaroni', quantity: '1 cup', category: 'grains' },
      { name: 'Fried onions', quantity: '1 cup', category: 'produce' },
      { name: 'Tomato sauce', quantity: '2 cups', category: 'canned' },
    ],
    steps: ['Cook rice, lentils, and pasta separately', 'Layer in serving bowls', 'Top with spicy tomato sauce', 'Garnish with fried onions', 'Serve hot'],
    prepTime: 20,
    cookTime: 40,
    diet: 'vegan',
    cuisines: ['egyptian'],
    images: [],
    rating: 4.5,
  },
  {
    id: '47',
    title: 'Filipino Adobo',
    description: 'Braised pork and chicken in soy sauce and vinegar.',
    ingredients: [
      { name: 'Pork belly', quantity: '400g', category: 'meat' },
      { name: 'Chicken thighs', quantity: '400g', category: 'meat' },
      { name: 'Soy sauce', quantity: '1/2 cup', category: 'condiments' },
      { name: 'White vinegar', quantity: '1/4 cup', category: 'condiments' },
      { name: 'Bay leaves', quantity: '4', category: 'spices' },
    ],
    steps: ['Brown meat pieces', 'Add soy sauce and vinegar', 'Simmer with bay leaves', 'Reduce until glossy', 'Serve with steamed rice'],
    prepTime: 15,
    cookTime: 45,
    diet: 'none',
    cuisines: ['filipino'],
    images: [],
    rating: 4.6,
  },
  {
    id: '48',
    title: 'Moroccan Couscous',
    description: 'Fluffy couscous with seven vegetables and aromatic broth.',
    ingredients: [
      { name: 'Couscous', quantity: '2 cups', category: 'grains' },
      { name: 'Mixed vegetables', quantity: '1kg', category: 'produce' },
      { name: 'Chickpeas', quantity: '1 can', category: 'canned' },
      { name: 'Ras el hanout', quantity: '2 tbsp', category: 'spices' },
      { name: 'Preserved lemons', quantity: '2', category: 'misc' },
    ],
    steps: ['Steam couscous until fluffy', 'Simmer vegetables with spices', 'Add chickpeas and preserved lemons', 'Serve couscous with vegetable stew', 'Garnish with fresh herbs'],
    prepTime: 30,
    cookTime: 45,
    diet: 'vegetarian',
    cuisines: ['moroccan'],
    images: [],
    rating: 4.5,
  },
  {
    id: '49',
    title: 'Korean BBQ Bulgogi',
    description: 'Marinated beef grilled and served with lettuce wraps.',
    ingredients: [
      { name: 'Ribeye steak', quantity: '600g', category: 'meat' },
      { name: 'Soy sauce', quantity: '1/4 cup', category: 'condiments' },
      { name: 'Asian pear', quantity: '1', category: 'produce' },
      { name: 'Sesame oil', quantity: '2 tbsp', category: 'condiments' },
      { name: 'Butter lettuce', quantity: '1 head', category: 'produce' },
    ],
    steps: ['Slice beef thinly', 'Marinate with pear and soy sauce', 'Grill over high heat', 'Serve with lettuce cups', 'Add kimchi and rice'],
    prepTime: 25,
    cookTime: 10,
    diet: 'none',
    cuisines: ['korean'],
    images: [],
    rating: 4.8,
  },
  {
    id: '50',
    title: 'Indian Masala Chai',
    description: 'Spiced tea with cardamom, ginger, and warm milk.',
    ingredients: [
      { name: 'Black tea', quantity: '4 tsp', category: 'misc' },
      { name: 'Milk', quantity: '2 cups', category: 'dairy' },
      { name: 'Cardamom pods', quantity: '6', category: 'spices' },
      { name: 'Fresh ginger', quantity: '1 inch', category: 'produce' },
      { name: 'Sugar', quantity: '2 tbsp', category: 'misc' },
    ],
    steps: ['Boil water with spices', 'Add tea and steep', 'Add milk and sugar', 'Simmer until frothy', 'Strain and serve hot'],
    prepTime: 5,
    cookTime: 10,
    diet: 'vegetarian',
    cuisines: ['indian'],
    images: [],
    rating: 4.7,
  },
];

// Create
router.post('/', async (req, res) => {
  try {
    const isDemo = process.env.DEMO_MODE === 'true';
    if (isDemo) {
      const recipe = { id: String(Date.now()), ...req.body };
      demoRecipes.push(recipe);
      return res.status(201).json(recipe);
    }
    const recipe = await Recipe.create(req.body);
    res.status(201).json(recipe);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// List with filters
router.get('/', async (req, res) => {
  try {
    const { q, ingredient, diet, maxPrepTime } = req.query;
    const isDemo = process.env.DEMO_MODE === 'true';
    if (isDemo) {
      let data = [...demoRecipes];
      if (q) data = data.filter(r => r.title.toLowerCase().includes(q.toLowerCase()));
      if (ingredient) data = data.filter(r => r.ingredients.some(i => i.name.toLowerCase().includes(ingredient.toLowerCase())));
      if (diet) data = data.filter(r => r.diet === diet);
      if (maxPrepTime) data = data.filter(r => r.prepTime <= Number(maxPrepTime));
      return res.json(data);
    }
    const query = {};
    if (diet) query.diet = diet;
    if (q) query.title = new RegExp(q, 'i');
    let mongoQuery = Recipe.find(query);
    const recipes = await mongoQuery.exec();
    // ingredient and maxPrepTime post-filtering for brevity
    let data = recipes;
    if (ingredient) data = data.filter(r => r.ingredients.some(i => i.name.toLowerCase().includes(ingredient.toLowerCase())));
    if (maxPrepTime) data = data.filter(r => r.prepTime <= Number(maxPrepTime));
    res.json(data);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Read one
router.get('/:id', async (req, res) => {
  try {
    const isDemo = process.env.DEMO_MODE === 'true';
    if (isDemo) {
      const recipe = demoRecipes.find(r => r.id === req.params.id);
      if (!recipe) return res.status(404).json({ message: 'Not found' });
      return res.json(recipe);
    }
    const recipe = await Recipe.findById(req.params.id);
    if (!recipe) return res.status(404).json({ message: 'Not found' });
    res.json(recipe);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Update
router.put('/:id', async (req, res) => {
  try {
    const isDemo = process.env.DEMO_MODE === 'true';
    if (isDemo) {
      const idx = demoRecipes.findIndex(r => r.id === req.params.id);
      if (idx === -1) return res.status(404).json({ message: 'Not found' });
      demoRecipes[idx] = { ...demoRecipes[idx], ...req.body };
      return res.json(demoRecipes[idx]);
    }
    const recipe = await Recipe.findByIdAndUpdate(req.params.id, req.body, { new: true });
    if (!recipe) return res.status(404).json({ message: 'Not found' });
    res.json(recipe);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Delete
router.delete('/:id', async (req, res) => {
  try {
    const isDemo = process.env.DEMO_MODE === 'true';
    if (isDemo) {
      const idx = demoRecipes.findIndex(r => r.id === req.params.id);
      if (idx === -1) return res.status(404).json({ message: 'Not found' });
      const removed = demoRecipes.splice(idx, 1);
      return res.json(removed[0]);
    }
    const recipe = await Recipe.findByIdAndDelete(req.params.id);
    if (!recipe) return res.status(404).json({ message: 'Not found' });
    res.json(recipe);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;